extends:
  - chartjs
  - plugin:markdown/recommended
  - plugin:@typescript-eslint/recommended

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2022
  sourceType: module

env:
  es2022: true
  browser: true
  node: true
  jasmine: true

plugins:
  - "@typescript-eslint"
  - prettier
  - html

rules:
  prettier/prettier: "error"
  semi: ["error", "never"]
  complexity: ["warn", 10]
  max-statements: ["warn", 30]
  no-var: "warn"
  prefer-const: ["warn", {"destructuring": "all"}]
  # turning off things conflicting with prettier
  indent: "off"
  comma-dangle: "off"
  comma-spacing: "off"
  comma-style: "off"
  object-curly-spacing: "off"
  space-before-function-paren: "off"
