extends:
  - chartjs
  - plugin:markdown/recommended

env:
  es2021: true
  browser: true
  node: true

parserOptions:
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    modules: true

plugins: ['html']

rules:
  complexity: ["warn", 10]
  max-statements: ["warn", 30]
  no-var: "warn"
  prefer-const: ["warn", {"destructuring": "all"}]
