import { defineConfigWithTheme } from 'vitepress'
import typedocSidebar from '../api/typedoc-sidebar.json'
import { version } from './docs-version.json'
import { chartEditor } from './markdown/chart-editor'
import type { ChartjsThemeConfig } from './theme-config'
import { versionsNav } from './versions'

// Which copy of the docs this build is: master, latest, next or an exact
// version. scripts/docs-config.sh rewrites docs-version.json before a release
// build; the committed default is master, so a local build or the dev server
// needs no extra step.
const docsVersion = version
const base = `/chartjs-plugin-zoom/${docsVersion}/`

export default defineConfigWithTheme<ChartjsThemeConfig>({
  // Light only, as the VuePress site was. Chart.js resolves its own defaults
  // for tick and grid colours, and several samples hard-code them, so a dark
  // page would leave the charts unreadable. Enabling the toggle means teaching
  // the samples about the theme first.
  appearance: false,
  base,
  description: 'A zoom and pan plugin for Chart.js >= 3.0.0',
  head: [['link', { rel: 'icon', href: `${base}favicon.ico` }]],
  lastUpdated: true,
  outDir: '../dist/docs',
  title: 'chartjs-plugin-zoom',

  markdown: {
    config: chartEditor,
  },

  vite: {
    // The samples import the freshly built bundle, which is rebuilt by
    // `npm run autobuild` while the dev server runs. Pre-bundling it would pin
    // the dev server to whichever copy existed at start-up.
    optimizeDeps: {
      exclude: ['chartjs-plugin-zoom'],
    },
  },

  themeConfig: {
    logo: '/favicon.ico',

    // Was the `footer` frontmatter on the VuePress home page, where the range
    // ended at a hard-coded 2021 and quietly went stale.
    footer: {
      message: 'MIT Licensed',
      copyright: 'Copyright © 2016-present chartjs-plugin-zoom contributors',
    },
    source: {
      repo: 'chartjs/chartjs-plugin-zoom',
      branch: 'master',
      dir: 'docs',
    },

    // Replaces vuepress-plugin-flexsearch.
    search: {
      provider: 'local',
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/chartjs/chartjs-plugin-zoom' },
    ],

    nav: [
      { text: 'Home', link: '/' },
      { text: 'Guide', link: '/guide/' },
      { text: 'API', link: '/api/' },
      { text: 'Samples', link: '/samples/basic' },
      {
        text: 'Ecosystem',
        items: [{ text: 'Awesome', link: 'https://github.com/chartjs/awesome' }],
      },
      await versionsNav(docsVersion),
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Getting Started', link: '/guide/' },
            { text: 'Integration', link: '/guide/integration' },
            { text: 'Usage', link: '/guide/usage' },
            { text: 'Options', link: '/guide/options' },
            { text: 'Animations', link: '/guide/animations' },
            { text: 'Developers', link: '/guide/developers' },
          ],
        },
      ],
      '/samples/': [
        { text: 'Basic', link: '/samples/basic' },
        {
          text: 'Wheel Zoom',
          collapsed: false,
          items: [
            { text: 'Category Scale', link: '/samples/wheel/category' },
            { text: 'Category Scale + minRange', link: '/samples/wheel/category-min-range' },
            { text: 'Logarithmic Scale', link: '/samples/wheel/log' },
            { text: 'Time Scale', link: '/samples/wheel/time' },
            { text: 'Over Scale Mode', link: '/samples/wheel/over-scale-mode' },
            { text: 'Click to Zoom', link: '/samples/wheel/click-zoom' },
          ],
        },
        {
          text: 'Drag to Zoom',
          collapsed: false,
          items: [
            { text: 'Category Scale', link: '/samples/drag/category' },
            { text: 'Linear Scales + maintainAspectRatio', link: '/samples/drag/linear-ratio' },
            { text: 'Linear Scales', link: '/samples/drag/linear' },
            { text: 'Logarithmic Scale', link: '/samples/drag/log' },
            { text: 'Reject outside chartArea', link: '/samples/drag/reject-outside' },
            { text: 'Time Scale', link: '/samples/drag/time' },
            { text: 'Timeseries Scale', link: '/samples/drag/timeseries' },
          ],
        },
        {
          text: 'Pan',
          collapsed: false,
          items: [
            { text: 'Pan Region', link: '/samples/pan/region' },
            { text: 'Pan Toggle', link: '/samples/pan/toggle' },
          ],
        },
        { text: 'Fetch Data', link: '/samples/fetch-data' },
        { text: 'API', link: '/samples/api' },
      ],
      // Generated by `npm run docs:api`; see typedoc.json.
      '/api/': [{ text: 'API', link: '/api/' }, ...typedocSidebar],
    },
  },
})
